CREATE USER STG IDENTIFIED BY "oracle" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO STG;
GRANT CREATE TABLE TO STG;
GRANT CREATE VIEW TO STG;
GRANT CREATE SEQUENCE TO STG;
GRANT CREATE PROCEDURE TO STG;
GRANT CREATE TRIGGER TO STG;
GRANT CREATE TYPE TO STG;


CREATE USER RDV IDENTIFIED BY "oracle" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO RDV;
GRANT CREATE TABLE TO RDV;
GRANT CREATE VIEW TO RDV;
GRANT CREATE SEQUENCE TO RDV;
GRANT CREATE PROCEDURE TO RDV;
GRANT CREATE TRIGGER TO RDV;
GRANT CREATE TYPE TO RDV;

CREATE USER IDL IDENTIFIED BY "oracle" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO IDL;
GRANT CREATE TABLE TO IDL;
GRANT CREATE VIEW TO IDL;
GRANT CREATE SEQUENCE TO IDL;
GRANT CREATE PROCEDURE TO IDL;
GRANT CREATE TRIGGER TO IDL;
GRANT CREATE TYPE TO IDL;

CREATE USER BDM IDENTIFIED BY "oracle" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDM;
GRANT CREATE TABLE TO BDM;
GRANT CREATE VIEW TO BDM;
GRANT CREATE SEQUENCE TO BDM;
GRANT CREATE PROCEDURE TO BDM;
GRANT CREATE TRIGGER TO BDM;
GRANT CREATE TYPE TO BDM;

GRANT SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, 
      DELETE ANY TABLE, CREATE ANY TABLE, ALTER ANY TABLE, 
      DROP ANY TABLE, CREATE ANY VIEW, DROP ANY VIEW,
      CREATE ANY PROCEDURE, DROP ANY PROCEDURE, 
      EXECUTE ANY PROCEDURE, CREATE ANY SEQUENCE,
      DROP ANY SEQUENCE, CREATE ANY TRIGGER, DROP ANY TRIGGER
TO BDM;

CREATE USER CDM IDENTIFIED BY "oracle" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO CDM;
GRANT CREATE TABLE TO CDM;
GRANT CREATE VIEW TO CDM;
GRANT CREATE SEQUENCE TO CDM;
GRANT CREATE PROCEDURE TO CDM;
GRANT CREATE TRIGGER TO CDM;
GRANT CREATE TYPE TO CDM;

CREATE USER FLOW IDENTIFIED BY "oracle" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO FLOW;
GRANT CREATE TABLE TO FLOW;
GRANT CREATE VIEW TO FLOW;
GRANT CREATE SEQUENCE TO FLOW;
GRANT CREATE PROCEDURE TO FLOW;
GRANT CREATE TRIGGER TO FLOW;
GRANT CREATE TYPE TO FLOW;

GRANT SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, 
      DELETE ANY TABLE, CREATE ANY TABLE, ALTER ANY TABLE, 
      DROP ANY TABLE, CREATE ANY VIEW, DROP ANY VIEW,
      CREATE ANY PROCEDURE, DROP ANY PROCEDURE, 
      EXECUTE ANY PROCEDURE, CREATE ANY SEQUENCE,
      DROP ANY SEQUENCE, CREATE ANY TRIGGER, DROP ANY TRIGGER
TO FLOW;

GRANT SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, 
      DELETE ANY TABLE, CREATE ANY TABLE, ALTER ANY TABLE, 
      DROP ANY TABLE, CREATE ANY VIEW, DROP ANY VIEW,
      CREATE ANY PROCEDURE, DROP ANY PROCEDURE, 
      EXECUTE ANY PROCEDURE, CREATE ANY SEQUENCE,
      DROP ANY SEQUENCE, CREATE ANY TRIGGER, DROP ANY TRIGGER
TO OLEG;


drop user BDM cascade;